### ISSUE TITLE
Field says Email, but Autocompletes Username

### ISSUE THREAD

**Issue by r-a-y** [hwdsbcommons/add-user-autocomplete#1]
_Ported over from older `add-user-autocomplete` issue:_

Could the "email" field be overwritten to say "Username" instead. The field is looking for username instead, and adding an email address fails. As a SuperAdmin the field reads Username or Email, but as a normal admin it only reads Email. 

![2017-03-01_13-59-19](https://cloud.githubusercontent.com/assets/480667/23477062/cb139524-fe8a-11e6-972b-036ae43ae96a.gif)

**Comment by r-a-y** [comment]
Fixed in commit https://github.com/hwdsbcommons/add-user-autocomplete/commit/5c101ded09578cc9b8750b526751fcb055921931.

Going to open a PR!

**Comment by r-a-y** [comment]
Actually, I find that I can search a user by email address even as a non-super-admin.  This plugin actually searches all the user DB columns and is not limited by username or email address:
https://github.com/hwdsbcommons/add-user-autocomplete/blob/master/add-user-autocomplete.php#L162

Tested on a fresh multisite install, not on the Commons though.

@mrjarbenne - Can you duplicate?

**Comment by mrjarbenne** [comment]
Yes. I can search by email address on the Commons. I wonder why I thought that was failing when I initially created the issue. It must not have been working for some reason. 

Thanks for fixing the label. Although email address works, the autocomplete does populate the Username, so it's probably a worthwhile change. If the PR is denied, perhaps the Superadmin "Email or Username" is a better label.

**Comment by r-a-y** [comment]
>  perhaps the Superadmin "Email or Username" is a better label.

I switched the labels to "Email or username", good call!

PR was accepted.
