### ISSUE TITLE
Add User Without Sending an Email Confirmation

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/add-user-autocomplete#2]
Can the superadmin "add user without sending out an email confirmation" functionality be added to subsite admins as well. We have users who don't have email addresses, so the email doesn't ever go and the user is never added.

![image](https://user-images.githubusercontent.com/480667/31632136-e4d857ca-b289-11e7-8dd5-3df60e6bc9ed.png)

**Comment by mrjarbenne** [comment]
Would it work to just comment out this line: 

https://github.com/hwdsbcommons/add-user-autocomplete/blob/c2b3fe4b08cc3d6044c84f342e80e39678aee41b/add-user-autocomplete.php#L86

That would mean everyone is just automatically added. 

(I probably need a companion plugin to allow people to remove themselves from sites. I'll search for that next)

**Comment by r-a-y** [comment]
I've added something for testing on production.  Give it a shot and let me know if it works for you.

**Comment by mrjarbenne** [comment]
Works great!
